export const LEGAL_ENTITY_NAME = '[Legal Entity Name Placeholder]'
export const LEGAL_ENTITY_ADDRESS = '[Registered Address Placeholder], Malta'
export const LEGAL_ENTITY_REGISTRATION = '[Company Registration Number Placeholder]'
export const LEGAL_ENTITY_VAT = '[VAT Number Placeholder]'
export const LEGAL_CONTACT_EMAIL = 'admin@rumenalexandrov.com'
export const LEGAL_DSA_CONTACT_EMAIL = 'admin@rumenalexandrov.com'
export const LEGAL_LAST_UPDATED = '6 June 2026'
